### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by Paul2708** [SpraxDev/Action-SpigotMC#13]
Hey, can you provide a README or tell me in this issue what the project is about?

Greetings
Paul

**Comment by SpraxDev** [comment]
Sure! I'm still working on the first release but I've created a `README.md` now, that I know the general structure of the project and figured out, how to write an Action.

Basically, this Action aims to make installing Spigot on GitHub Actions easier and faster.
I have a project on GitHub, that uses NMS calls instead of Reflections, needing nearly 10 different spigot versions to be present in the local maven repository to compile the project.

And installing all those versions does not only take 30+ minutes, but also makes the workflow file harder to read.

And because these compiled Spigot binaries contain licensed parts that may not be distributed, they cannot be hosted on a public repository.

But with this Action, you just provide a list of versions and it does everything for you (+ multi-threading when possible).

**Comment by Paul2708** [comment]
Hey, thanks for providing these information. It seems to be very useful!
